# Generated by Django 5.2.4 on 2025-07-14 01:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='isbn',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='El ISBN debe tener exactamente 13 dígitos.', regex='^\\d{13}$')], verbose_name='ISBN'),
        ),
    ]
